name: gaussian_splatting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - plyfile
  - tqdm
  - mkl=2020.2
  - scipy
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.4.0+cu118
    - torchvision==0.19.0+cu118
    - torchaudio==2.4.0+cu118
    - opencv-python==4.5.5.64
    - numpy<2
    - joblib
    - huggingface_hub==0.25.2
    - transformers==4.45.2
    - diffusers==0.25.1
    - accelerate
    - peft>=0.17.0
    - joblib
    - typing-extensions>=4.8.0
    - einops
