name: sam3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pillow
  - matplotlib
  - requests
  - pip:
    - torch>=2.6.0
    - torchvision
    - triton
    - numpy<2,>=1.26
    - transformers>=4.45.0
    - opencv-python<5
    - gradio_client
    - accelerate
    - setuptools<82.0.0
    - einops
    - pycocotools
    - tqdm
    - diffusers
    - peft